// Fictional exercise scenarios, spread across continents and event types.
window.EXTRA_SCENARIOS = [
['weather','Alaska',64,-149,'Blizzard closes regional airfields','High','snow','Coordinate warming centers and alternate airlift routes.'],
['weather','British Columbia',53,-125,'Wildfire evacuation watch','High','fire','Review evacuation corridors and smoke exposure plans.'],
['weather','Central United States',39,-97,'Tornado outbreak drill','High','storm','Activate shelter messaging and damage assessment teams.'],
['weather','Caribbean',18,-66,'Storm surge coastal advisory','High','water','Prepare coastal shelters and maritime evacuation routes.'],
['weather','Amazon Basin',-4,-60,'River flood response','Moderate','water','Stage rescue boats and drinking-water supplies.'],
['weather','Southern Chile',-43,-73,'Volcanic ash aviation watch','Moderate','volcano','Assess ash exposure and alternate flight paths.'],
['weather','Iceland',65,-19,'Volcanic activity exercise','High','volcano','Coordinate aviation advisories and local evacuation planning.'],
['weather','Scandinavia',65,20,'Severe winter weather','Moderate','snow','Check transport continuity and isolated communities.'],
['weather','Mediterranean',38,15,'Coastal heat and fire risk','Moderate','fire','Prepare cooling centers and firefighting resources.'],
['weather','East Africa',1,37,'Flash flood response drill','High','water','Identify safe crossings and emergency supply routes.'],
['weather','Arabian Peninsula',24,47,'Dust storm visibility alert','Moderate','wind','Review road safety and airport diversion plans.'],
['weather','Indian subcontinent',23,80,'Monsoon rainfall exercise','High','water','Check flood defenses and shelter readiness.'],
['weather','Himalayan region',29,85,'Landslide access disruption','Moderate','quake','Locate alternate access routes for relief teams.'],
['weather','Japan',36,139,'Earthquake and tsunami drill','High','quake','Review coastal alerts and emergency assembly points.'],
['weather','New Zealand',-42,173,'Seismic infrastructure inspection','Moderate','quake','Coordinate bridge inspections and utility assessments.'],
['weather','Western Australia',-24,119,'Extreme heat resource watch','Moderate','heat','Stage water supplies and heat relief resources.'],
['homeland','Pacific Northwest',47,-122,'Search-and-rescue mobilization','Moderate','rescue','Coordinate volunteer teams and terrain search sectors.'],
['homeland','Great Lakes region',43,-85,'Hazardous material response drill','High','hazmat','Establish isolation zones and public information channels.'],
['homeland','Central Mexico',20,-100,'Mass gathering readiness check','Low','shield','Verify medical support and crowd management plans.'],
['homeland','Northern Brazil',-2,-48,'Emergency shelter coordination','Moderate','rescue','Confirm shelter staffing and accessible transport.'],
['homeland','Andean region',-17,-68,'Remote community relief exercise','Moderate','rescue','Review relief staging and high-altitude access.'],
['homeland','United Kingdom',54,-2,'Airport security exercise','Low','aircraft','Validate interagency reporting and passenger communication.'],
['homeland','Central Europe',50,14,'Rail evacuation coordination','Moderate','rail','Coordinate alternate transport and passenger assistance.'],
['homeland','West Africa',7,-5,'Public health logistics exercise','Moderate','medical','Prepare mobile treatment teams and supply distribution.'],
['homeland','Southeast Asia',14,101,'Urban emergency response drill','Low','rescue','Validate dispatch coordination and medical surge capacity.'],
['homeland','South Korea',37,127,'Civil preparedness exercise','Low','shield','Test shelter access and emergency communication procedures.'],
['foreign','Arctic sea lanes',68,45,'Polar maritime activity watch','Moderate','ship','Assess shipping exposure and emergency support options.'],
['foreign','Baltic Sea',57,20,'Foreign maneuver monitoring','Moderate','radar','Review regional logistics and transport dependencies.'],
['foreign','Eastern Mediterranean',34,30,'Airspace restriction scenario','High','aircraft','Assess travel impacts and alternate aviation routes.'],
['foreign','Persian Gulf',26,54,'Maritime escort exercise','High','ship','Review sea lane access and cargo contingencies.'],
['foreign','Central Asia',43,68,'Border tension planning scenario','Moderate','radar','Review regional transit and relief supply contingencies.'],
['foreign','Indian Ocean',-4,72,'Naval activity exercise','Moderate','ship','Brief leadership on shipping and overseas dependencies.'],
['foreign','Taiwan Strait',24,119,'Regional air activity scenario','High','aircraft','Assess transport continuity and regional supply chains.'],
['foreign','South Pacific',-18,-170,'Remote maritime patrol watch','Low','ship','Review patrol coordination and ocean rescue coverage.'],
['infra','Northeastern United States',41,-74,'Rail signal outage drill','Moderate','rail','Arrange alternate transport and safe service recovery.'],
['infra','Canadian Prairies',51,-106,'Pipeline interruption exercise','Moderate','power','Evaluate fuel reserves and alternate delivery networks.'],
['infra','Panama',9,-80,'Canal traffic restriction','High','ship','Identify alternate cargo routes and delivery windows.'],
['infra','Southern Argentina',-46,-68,'Remote communications outage','Moderate','comms','Activate backup radio links and relay stations.'],
['infra','Iberian Peninsula',40,-4,'Regional water supply disruption','High','water','Confirm emergency water distribution and storage.'],
['infra','Northern Europe',60,10,'Undersea cable continuity drill','Moderate','comms','Review alternate communication links and redundancy.'],
['infra','North Africa',30,10,'Fuel terminal continuity exercise','Moderate','power','Check reserve capacity and alternate loading facilities.'],
['infra','Southern India',13,78,'Regional grid load exercise','High','power','Prioritize hospitals and essential public services.'],
['infra','Singapore Strait',1,104,'Port cargo backlog scenario','Moderate','ship','Assess alternate ports and essential freight priorities.'],
['infra','Eastern Australia',-28,153,'Telecommunications restoration','Moderate','comms','Stage backup links and restoration crews.'],
['infra','Fiji',-18,178,'Island airport continuity drill','Low','aircraft','Verify alternate air access and essential cargo schedules.'],
['homeland','Hawaii',21,-158,'Island medical surge drill','Moderate','medical','Coordinate patient transport and emergency supply reserves.'],
['weather','Greenland',67,-43,'Polar storm logistics watch','Moderate','snow','Confirm cold-weather transport and emergency shelter plans.'],
['homeland','Madagascar',-19,47,'Coastal rescue coordination','Moderate','rescue','Stage rescue assets and emergency communications.']
].map((s,i)=>({id:i+13,cat:s[0],region:s[1],lat:s[2],lon:s[3],title:s[4],priority:s[5],icon:s[6],action:s[7],text:'Fictional training scenario. '+s[7]}));
